# Generated by Django 4.1.3 on 2022-11-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_language_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='language',
            new_name='languages',
        ),
    ]
